//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public authors()
        {
            this.titleauthor = new HashSet<titleauthor>();
        }

        [Required]
        [Display(Name ="Author's ID")]
        [RegularExpression(@"\d\d\d"+"-"+@"\d\d"+"-"+@"\d\d\d\d", ErrorMessage = "Author's ID is not valid. (Example: \"123-45-6789\")")]
        public string au_id { get; set; }

        [Required]
        [Display(Name = "Last name")]
        [MaxLength(40)]
        public string au_lname { get; set; }

        [Required]
        [Display(Name = "First name")]
        [MaxLength(20)]
        public string au_fname { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        [MaxLength(12)]
        public string phone { get; set; }

        [Display(Name = "Address")]
        [MaxLength(40)]
        public string address { get; set; }

        [Display(Name = "City")]
        [MaxLength(20)]
        public string city { get; set; }

        [Display(Name = "State")]
        [MaxLength(2)]
        public string state { get; set; }

        [Display(Name = "Zip Code")]
        [RegularExpression(@"\d\d\d\d\d", ErrorMessage = "Zip Code is not valid. (Example: \"12345\")")]
        public string zip { get; set; }

        [Display(Name = "Contract")]
        public bool contract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titleauthor> titleauthor { get; set; }
    }
}
