//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jobs()
        {
            this.employee = new HashSet<employee>();
        }
        [Display(Name = "Job ID")]
        [Required]
        [Range(0, Int16.MaxValue)]
        public short job_id { get; set; }
        [Display(Name = "Job Description")]
        [Required]
        [MaxLength(50)]
        public string job_desc { get; set; }
        [Display(Name = "Min Level")]
        [Required]
        [Range(10,250)]
        public byte min_lvl { get; set; }
        [Display(Name = "Min Level")]
        [Required]
        [Range(10, 250)]
        public byte max_lvl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
    }
}
