//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_info
    {
        [Display(Name = "Publisher's ID")]
        [Required]
        [MaxLength(4)]
        public string pub_id { get; set; }
        public byte[] logo { get; set; }

        public string pr_info { get; set; }
    
        public virtual publishers publishers { get; set; }
    }
}
