//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Models
{

    public partial class pub_info
    {
        [Display(Name = "Publisher's ID")]
        [Required]
        [MaxLength(4)]
        public string pub_id { get; set; }

        [Display(Name = "Logo")]
        public byte[] logo { get; set; }

        public HttpPostedFileBase file { get; set; }

        [Display(Name = "Publisher's Info")]
        [DataType(DataType.MultilineText)]
        public string pr_info { get; set; }

        public virtual publishers publishers { get; set; }
    }

    public static class HtmlExtensions {
        public static MvcHtmlString Image(this HtmlHelper html, byte[] image) {
            if (image != null) {
                var img = String.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(image));
                return new MvcHtmlString("<img src='" + img + "' />");
            }
            return new MvcHtmlString("");
        }
    }
}
