//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publishers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publishers()
        {
            this.employee = new HashSet<employee>();
            this.titles = new HashSet<titles>();
        }

        [Display(Name = "Publisher's ID")]
        [Required]
        [MaxLength(4)]
        [RegularExpression(@"99\d\d", ErrorMessage = "Publisher's ID is not valid. ID has to be of form 99xx)")]
        public string pub_id { get; set; }
        [Display(Name = "Publisher's Name")]
        [MaxLength(40)]
        public string pub_name { get; set; }
        [Display(Name = "City")]
        [MaxLength(20)]
        public string city { get; set; }
        [Display(Name = "State")]
        [MaxLength(2)]
        public string state { get; set; }
        [Display(Name = "Country")]
        [MaxLength(30)]
        public string country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
        public virtual pub_info pub_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titles> titles { get; set; }
    }
}
