//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sales
    {
        [Required]
        [Display(Name ="Store")]
        public string stor_id { get; set; }

        [Required]
        [Display(Name ="Order Number")]
        public string ord_num { get; set; }

        [Required]
        [Display(Name ="Order Date")]
        public System.DateTime ord_date { get; set; }
        
        [Required]
        [Display(Name = "Quantity")]
        public short qty { get; set; }

        [Required]
        [Display(Name ="Payment Terms")]
        public string payterms { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string title_id { get; set; }
    
        public virtual stores stores { get; set; }

        public virtual titles titles { get; set; }
    }
}
