//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class titles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public titles()
        {
            this.roysched = new HashSet<roysched>();
            this.sales = new HashSet<sales>();
            this.titleauthor = new HashSet<titleauthor>();
        }

        [Required]
        [Display(Name = "title ID")]
        [RegularExpression("\\w\\w\\d\\d\\d\\d",
            ErrorMessage = "Title's ID is not valid. (Example: \"BU1234\")")]
        public string title_id { get; set; }

        [Required]
        [Display(Name = "Title")]
        [MaxLength(80)]
        public string title { get; set; }

        [Display(Name = "Type")]
        [Required]
        [MaxLength(12)]
        public string type { get; set; }

        [Display(Name = "Publisher Name")]
        [MaxLength(4)]
        public string pub_id { get; set; }

        [Display(Name = "Price")]
        public Nullable<decimal> price { get; set; }

        [Display(Name = "In Advance")]
        public Nullable<decimal> advance { get; set; }

        [Display(Name = "Royalty")]
        public Nullable<int> royalty { get; set; }

        [Display(Name = "Sales per Year")]
        public Nullable<int> ytd_sales { get; set; }

        [Display(Name = "Notes")]
        [MaxLength(200)]
        public string notes { get; set; }

        [Required]
        [Display(Name = "Publication Date")]
        public System.DateTime pubdate { get; set; }
    
        public virtual publishers publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roysched> roysched { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<titleauthor> titleauthor { get; set; }
    }
}