//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class titleauthor
    {
        [Display(Name ="Author's ID")]
        [Required]
        public string au_id { get; set; }

        [Display(Name ="Title")]
        [Required]
        public string title_id { get; set; }

        [Display(Name ="Author Order")]
        [MaxLength(3)]
        public Nullable<byte> au_ord { get; set; }

        [Display(Name = "Royal Typer")]
        public Nullable<int> royaltyper { get; set; }

        public virtual authors authors { get; set; }

        public virtual titles titles { get; set; }
    }
}
